# Generated by Django 6.0 on 2025-12-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Event_Name', models.CharField(max_length=100)),
                ('Registration_Status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Hold', 'Hold')])),
            ],
        ),
    ]
