# Generated by Django 6.0 on 2025-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Client_Name', models.CharField(max_length=100)),
                ('Contact_Number', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Available', max_length=100)),
            ],
        ),
    ]
