# Generated by Django 6.0 on 2025-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Amount', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=200)),
                ('Payment_Mode', models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Credit', 'Credit'), ('Debit', 'Debit')], default='UPI', max_length=100)),
                ('Optional_Notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
