# Generated by Django 6.0 on 2025-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventorystockdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_Name', models.CharField(max_length=100)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Stock_Quantity', models.IntegerField()),
                ('Purchase_Date', models.DateField()),
                ('Reorder_Level', models.CharField(max_length=100)),
            ],
        ),
    ]
